name: Percy.io
on: [push]
jobs:
  percy_io:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          registry-url: https://npm.pkg.github.com/
          cache: "npm"
      - name: rnstall dependencies
        run: npm ci
      - name: run percy
        run: percy exec -- gatsby build
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
