name: Percy.io
on: [pull_request]

jobs:
  percy_io:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "npm"
      - name: install dependencies
        run: npm ci
      - name: run percy
        run: npm run percy exec -- gatsby build
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
