name: "Pull Request Linting"

on: [pull_request]

jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          check-latest: true
          cache: "npm"
      - name: Run eslint
        run: |
          npm ci
          npm run lint
